# The Gram-Schmidt Process

The Gram-Schmidt process is a method for constructing an orthonormal basis of a space that a set of given vectors span. It can also be used to determine the dimension of that space, which may be different than the dimension of the vectors themselves or the number of vectors provided to span the space. 

The Gram Schmidt process involves taking a list of vectors and form an orthonormal basis from this set. The procedure allows us to determine the dimension of the space spanned by the basis vectors, which is equal to or less than the space which the vectors sit. 

In [1]:
import numpy as np 
import numpy.linalg as la

verySmallNumber = 1e-14 

# First function will perform the procedure on 4 basis vectors
# Will then take this list of vectors as the columns of a matrix 4
# Will then go through the vectors one at a time and set them to be orthogonal to add all the vectors that came before it. Before normalising. 

def gsBasis4(A) :
    B = np.array(A, dtype=np.float_)
    
    # Zeroth column has no other vectors to make it normal to, so only need to normalise it. (Divide by its modulus)
    B[:,0] = B[:,0] / la.norm(B[:,0])
    
    # First column: Need to subtract any overlap with our new zeroth vector
    B[:,1] = B[:,1] - B[:,1] @ B[:,0] * B[:,0]
    
    # If there is anything left after that subtraction, then B[:,1] is linearly independent of B[:,0]
    # If this is the case then can normalise it, otherwise the vector will be set to zero. 
    
    if la.norm(B[:,1]) > verySmallNumber :
        B[:,1] = B[:,1] / la.norm(B[:,1])
    else: 
        B[:,1] = np.zeros_like(B[:,1])
        
    # Repeat for column 2
    B[:,2] = B[:,2] - B[:,2] @ B[:,0] * B[:,0]
    B[:,2] = B[:,2] - B[:,2] @ B[:,1] * B[:,1]
    
    if la.norm(B[:,2]) > verySmallNumber :
        B[:,2] = B[:,2] / la.norm(B[:,2])
    else: 
        B[:,2] = np.zeros_like(B[:,2])
    
    
    # Column 3
    B[:,3] = B[:,3] - B[:,3] @ B[:,0] * B[:,0]
    B[:,3] = B[:,3] - B[:,3] @ B[:,1] * B[:,1]
    B[:,3] = B[:,3] - B[:,3] @ B[:,2] * B[:,2]
    
    if la.norm(B[:,3]) > verySmallNumber :
        B[:,3] = B[:,3] / la.norm(B[:,3])
    else : 
        B[:,3] = np.zeros_like(B[:,3])
        
    return B

# I am now going to adapt the function to generalise the procedure
# Using a for loop to iterate the process for each vector rather than repeating the code.

def gsBasis(A) :
    B = np.array(A, dtype=np.float_)
    
    # Loop over all vectors, starting with zero, label with i 
    for i in range(B.shape[1]) :
        # Loop over all previous vectors, j, to subtract
        for j in range(i): 
            #Subtract overlap with previous vectors
            B[:,i] = B[:,i] - B[:,i] @ B[:, j] * B[:,j]
        # Normalisation test for B[:,i]
        if la.norm(B[:,i]) > verySmallNumber :
            B[:, i] = B[:, i] / la.norm(B[:, i])
        else: 
            B[:, i] = np.zeros_like(B[:, i])
            
    return B


# Function to use the GS process to calc the dimension spanned by the list of vectors
# Since each vector is normalised to one, or is zero, the sum of all the norms will be the dimension

def dimensions(A) : 
    return np.sum(la.norm(gsBasis(A), axis=0))

In [2]:
V = np.array([[1,0,2,6],
              [0,1,8,2],
              [2,8,3,1],
              [1,-6,2,3]], dtype=np.float_)
gsBasis4(V)

array([[ 0.40824829, -0.1814885 ,  0.04982278,  0.89325973],
       [ 0.        ,  0.1088931 ,  0.99349591, -0.03328918],
       [ 0.81649658,  0.50816781, -0.06462163, -0.26631346],
       [ 0.40824829, -0.83484711,  0.07942048, -0.36063281]])

In [3]:
A = np.array([[3,2,3],
              [2,5,-1],
              [2,4,8],
              [12,2,1]], dtype=np.float_)
gsBasis(A)

array([[ 0.23643312,  0.18771349,  0.22132104],
       [ 0.15762208,  0.74769023, -0.64395812],
       [ 0.15762208,  0.57790444,  0.72904263],
       [ 0.94573249, -0.26786082, -0.06951101]])

In [4]:
dimensions(A)

3.0

In [5]:
B = np.array([[6,2,1,7,5],
              [2,8,5,-4,1],
              [1,-6,3,2,8]], dtype=np.float_)
gsBasis(B)

array([[ 0.93704257, -0.12700832, -0.32530002,  0.        ,  0.        ],
       [ 0.31234752,  0.72140727,  0.61807005,  0.        ,  0.        ],
       [ 0.15617376, -0.6807646 ,  0.71566005,  0.        ,  0.        ]])

In [6]:
dimensions(B)

3.0

In [7]:
C = np.array([[1,0,2],
              [0,1,-3],
              [1,0,2]], dtype=np.float_)
gsBasis(C)

array([[0.70710678, 0.        , 0.        ],
       [0.        , 1.        , 0.        ],
       [0.70710678, 0.        , 0.        ]])

In [8]:
dimensions(C)

2.0